import { Product, Order, Customer } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Luxe LED Vanity Mirror',
    image: 'https://picsum.photos/200/200?random=1',
    type: 'LED Mirror',
    shape: 'Rectangle',
    dimensions: '60x80cm',
    price: 1500,
    stock: 12,
    status: 'In Stock',
    isVisible: true,
  },
  {
    id: 'p2',
    name: 'Gold Sunburst Decor',
    image: 'https://picsum.photos/200/200?random=2',
    type: 'Decorative',
    shape: 'Round',
    dimensions: '90cm Dia',
    price: 2200,
    stock: 3,
    status: 'Low Stock',
    isVisible: true,
  },
  {
    id: 'p3',
    name: 'Minimalist Black Frame',
    image: 'https://picsum.photos/200/200?random=3',
    type: 'Wall Mirror',
    shape: 'Round',
    dimensions: '50cm Dia',
    price: 850,
    stock: 0,
    status: 'Out of Stock',
    isVisible: true,
  },
  {
    id: 'p4',
    name: 'Frameless Beveled Edge',
    image: 'https://picsum.photos/200/200?random=4',
    type: 'Wall Mirror',
    shape: 'Rectangle',
    dimensions: '120x60cm',
    price: 1100,
    stock: 25,
    status: 'In Stock',
    isVisible: true,
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'c1',
    name: 'Amine Benali',
    phone: '+212 661-123456',
    address: '12 Bd Zerktouni',
    city: 'Casablanca',
    totalSpent: 4500,
    orderCount: 2,
  },
  {
    id: 'c2',
    name: 'Salma Bennani',
    phone: '+212 663-987654',
    address: '45 Ave Mohammed VI',
    city: 'Marrakech',
    totalSpent: 12000,
    orderCount: 1,
  },
  {
    id: 'c3',
    name: 'Youssef El Alami',
    phone: '+212 661-554433',
    address: '88 Rue des Consuls',
    city: 'Rabat',
    totalSpent: 1500,
    orderCount: 1,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    customerId: 'c1',
    customerName: 'Amine Benali',
    type: 'Standard',
    date: '2023-10-25',
    totalPrice: 1500,
    paidAmount: 1500,
    status: 'Completed',
    paymentMethod: 'Card',
    items: [MOCK_PRODUCTS[0]],
  },
  {
    id: 'ord-1002',
    customerId: 'c2',
    customerName: 'Salma Bennani',
    type: 'Custom Project',
    date: '2023-10-26',
    totalPrice: 12000,
    paidAmount: 6000,
    status: 'In Production',
    paymentMethod: 'Transfer',
    customDetails: {
      width: 200,
      height: 150,
      shape: 'Rectangle',
      frameType: 'Antique Brass',
      frameColor: 'Gold',
      isInstallationRequired: true,
    },
  },
  {
    id: 'ord-1003',
    customerId: 'c3',
    customerName: 'Youssef El Alami',
    type: 'Standard',
    date: '2023-10-27',
    totalPrice: 1500,
    paidAmount: 1500,
    status: 'New',
    paymentMethod: 'Cash',
    items: [MOCK_PRODUCTS[0]],
  },
];